apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-sql
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: mmkeyvault25
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 5af60a67-60b0-4d5c-b1ab-3cc4db4329f6
    objects:  |
      array:
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret        
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
