apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-edit
  namespace: web
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "{{WEB_GROUP_ID}}"
  apiGroup: rbac.authorization.k8s.io